name: test-linters

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  test-clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: '.'
          exclude: './third_party ./external'
          extensions: 'h,c,cpp'
          clangFormatVersion: 6
          style: Google
