name: Wheels
"on":
  pull_request: ~
  push:
    branches:
      - "master"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - { name: "ubuntu-20.04", needs_qemu: true }
          - { name: "windows-2019", needs_qemu: false }
          - { name: "macOS-11", needs_qemu: false }
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v3
      - uses: docker/setup-qemu-action@v2
        if: ${{ matrix.os.needs_qemu }}
      - name: Install cibuildwheel
        run: python -m pip install setuptools cibuildwheel==2.13.0 cython
      - name: Build wheels
        run: |
          cythonize python/libsettings.pyx
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_SKIP: cp36-*
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v3
      - name: Install build
        run: python -m pip install setuptools build cython
      - name: Build wheels
        run: |
          cythonize python/libsettings.pyx
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.tar.gz
