name: Wheels

on:
  pull_request: ~
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.0 cython
      - name: Build wheels
        run: |
          cythonize python/libsettings.pyx
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_SKIP: cp36-*
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v3
      - name: Install build
        run: python -m pip install build cython
      - name: Build wheels
        run: |
          cythonize python/libsettings.pyx
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.tar.gz
